name: "CI"

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-22.04"

    steps:
      - uses: "actions/checkout@v3"

      - name: "Use Node.js LTS"
        uses: "actions/setup-node@v3"
        with:
          node-version: "18.17.x"
          cache: "npm"

      - name: "Install dependencies"
        run: "npm ci"

      - name: "Compile SCSS"
        run: "make build"

      - name: "Create dist archive"
        run: "make VERSION=0.0.0-dev dist"
