name: "Release"
run-name: "Release ${{ github.ref_name }} (${{ github.run_number }})"

on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: "boolean"
        description: "Dry-run (no push, no release)"
        default: false

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-22.04"

    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
          token: ${{ secrets.PUSH_TOKEN }}

      - name: "Git user"
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: "Use Node.js LTS"
        uses: "actions/setup-node@v3"
        with:
          node-version: "18.17.x"
          cache: "npm"

      - name: "Install dependencies"
        run: "npm ci"

      - name: "Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN_ARGS: ${{ github.event.inputs.dry_run == 'true' && '--no-git.push --no-github.release' || '' }}
        run: npm run release -- --ci --verbose ${DRY_RUN_ARGS}
